version: "2"

services:
    orderer0.metasurance.com:
        container_name: orderer0.metasurance.com
        extends:
            file: peer-base.yaml
            service: orderer-base
        volumes:
            - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer0.genesis.block
            - ../crypto-config/ordererOrganizations/metasurance.com/orderers/orderer0.metasurance.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/metasurance.com/orderers/orderer0.metasurance.com/tls/:/var/hyperledger/orderer/tls
            - orderer0.metasurance.com:/var/hyperledger/production/orderer
        ports:
            - 7050:7050

    peer0.insurer.metasurance.com:
        container_name: peer0.insurer.metasurance.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.insurer.metasurance.com
            - CORE_PEER_ADDRESS=peer0.insurer.metasurance.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.insurer.metasurance.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.user.metasurance.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurer.metasurance.com:7051
            - CORE_PEER_LOCALMSPID=InsurerMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.insurer.metasurance.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/insurer.metasurance.com/peers/peer0.insurer.metasurance.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/insurer.metasurance.com/peers/peer0.insurer.metasurance.com/tls:/etc/hyperledger/fabric/tls
            - peer0.insurer.metasurance.com:/var/hyperledger/production
        ports:
            - 7051:7051

    peer0.user.metasurance.com:
        container_name: peer0.user.metasurance.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.user.metasurance.com
            - CORE_PEER_ADDRESS=peer0.user.metasurance.com:8051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODEADDRESS=peer0.user.metasurance.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.user.metasurance.com:8051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurer.metasurance.com:7051
            - CORE_PEER_LOCALMSPID=UserMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.user.metasurance.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/user.metasurance.com/peers/peer0.user.metasurance.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/user.metasurance.com/peers/peer0.user.metasurance.com/tls:/etc/hyperledger/fabric/tls
            - peer0.user.metasurance.com:/var/hyperledger/production
        ports:
            - 8051:8051

    peer0.assets.metasurance.com:
        container_name: peer0.assets.metasurance.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.assets.metasurance.com
            - CORE_PEER_ADDRESS=peer0.assets.metasurance.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.assets.metasurance.com:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.assets.metasurance.com:9051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurer.metasurance.com:7051
            - CORE_PEER_LOCALMSPID=AssetsMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.assets.metasurance.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/assets.metasurance.com/peers/peer0.assets.metasurance.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/assets.metasurance.com/peers/peer0.assets.metasurance.com/tls:/etc/hyperledger/fabric/tls
            - peer0.assets.metasurance.com:/var/hyperledger/production
        ports:
            - 9051:9051

    peer0.exampleadmin.metasurance.com:
        container_name: peer0.exampleadmin.metasurance.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.exampleadmin.metasurance.com
            - CORE_PEER_ADDRESS=peer0.exampleadmin.metasurance.com:10051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
            - CORE_PEER_CHAINCODEADDRESS=peer0.exampleadmin.metasurance.com:10052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exampleadmin.metasurance.com:10051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurer.metasurance.com:7051
            - CORE_PEER_LOCALMSPID=MetaAdminMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.exampleadmin.metasurance.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/exampleadmin.metasurance.com/peers/peer0.exampleadmin.metasurance.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/exampleadmin.metasurance.com/peers/peer0.exampleadmin.metasurance.com/tls:/etc/hyperledger/fabric/tls
            - peer0.exampleadmin.metasurance.com:/var/hyperledger/production
        ports:
            - 10051:10051

    ca.insurer.metasurance.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-insurer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurer.metasurance.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/738cd98f51508b98d0b01afdc62ff7b58f69c68c22f918011293f2c24a3a9c70_sk
            - FABRIC_CA_SERVER_PORT=7054
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurer.metasurance.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/738cd98f51508b98d0b01afdc62ff7b58f69c68c22f918011293f2c24a3a9c70_sk -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/insurer.metasurance.com/ca/:/etc/hyperledger/fabric-ca-server-config

    ca.user.metasurance.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-user
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.user.metasurance.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2fe9cb4405a39947fcc5a93f946738d1c197bd797dab58bd45c2ae646e788665_sk
            - FABRIC_CA_SERVER_PORT=8054
        ports:
            - "8054:8054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.user.metasurance.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2fe9cb4405a39947fcc5a93f946738d1c197bd797dab58bd45c2ae646e788665_sk -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/user.metasurance.com/ca/:/etc/hyperledger/fabric-ca-server-config

    ca.assets.metasurance.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-assets
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.assets.metasurance.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f86e4cb5f54cb7ea110a7801b9e409d3cc0326d53ee20c8e213002769170d3d1_sk
            - FABRIC_CA_SERVER_PORT=9054
        ports:
            - "9054:9054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.assets.metasurance.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f86e4cb5f54cb7ea110a7801b9e409d3cc0326d53ee20c8e213002769170d3d1_sk -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/assets.metasurance.com/ca/:/etc/hyperledger/fabric-ca-server-config

    ca.exampleadmin.metasurance.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-exampleadmin
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exampleadmin.metasurance.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/855462350c417185dfb0f75eec0f1ad91bae63944d97ef8a2f1fd7f99ee696a6_sk
            - FABRIC_CA_SERVER_PORT=10054
        ports:
            - "10054:10054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.exampleadmin.metasurance.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/855462350c417185dfb0f75eec0f1ad91bae63944d97ef8a2f1fd7f99ee696a6_sk -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/exampleadmin.metasurance.com/ca/:/etc/hyperledger/fabric-ca-server-config
