OrdererOrgs:
    - Name: Orderer
      Domain: metasurance.com
      EnableNodeOUs: true
      Template:
          Count: 1

PeerOrgs:
    - Name: Insurer
      Domain: insurer.metasurance.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: User
      Domain: user.metasurance.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Assets
      Domain: assets.metasurance.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: MetaAdmin
      Domain: exampleadmin.metasurance.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1
