test:
    name: caliper_benchmark
    description: test benchmark
    workers:
      number: 4
    rounds:
      # - label: Read User
      #   description: Query User benchmark
      #   txDuration: 30
      #   rateControl:
      #     type: fixed-load
      #     opts:
      #       transactionLoad: 2
      #   workload:
      #     module: benchmarks/callbacks/createProfileBenchmark.js
      #     arguments:
      #       times: 10
      # - label: Get Policies
      #   description: Show all Policies
      #   txDuration: 30
      #   rateControl:
      #     type: fixed-rate
      #     opts:
      #       transactionLoad: 2
      #   workload:
      #     module: benchmarks/callbacks/getPolicyBenchmark.js
      #     arguments:
      #       policies: 10
      - label: Get Assets
        description: Show registered Assets
        txDuration: 30
        rateControl:
          type: fixed-load
          opts:
            transactionLoad: 2
        workload:
          module: benchmarks/callbacks/getAssetBenchmark.js
          arguments:
            assets: 10
