test:
    name: caliper_benchmark
    description: test benchmark
    workers:
      number: 1
    rounds:
      - label: Read User
        description: Query User benchmark
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 600
        workload:
          module: benchmarks/callbacks/createProfileBenchmark.js
          arguments:
            times: 10
      - label: Get Policies
        description: Show all Policies
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 600
        workload:
          module: benchmarks/callbacks/getPolicyBenchmark.js
          arguments:
            policies: 10
      - label: Get Assets
        description: Show registered Assets
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 600
        workload:
          module: benchmarks/callbacks/getAssetBenchmark.js
          arguments:
            assets: 10
      - label: View issued policies
        description: Show issued policies
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 600
        workload:
          module: benchmarks/callbacks/mapPolicyUser.js
          arguments:
            issues: 10
      - label: pay premium
        description: Pay the premium
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 600
        workload:
          module: benchmarks/callbacks/payPremium.js
          arguments:
            issues: 10
      - label: claim policy
        description: Claim a policy
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 600
        workload:
          module: benchmarks/callbacks/claimBenchmark.js
          arguments:
            issues: 10
