test:
    name: caliper_benchmark
    description: test benchmark
    workers:
      number: 1
    rounds:
      - label: createUser
        description: Query User benchmark
        txDuration: 30
        rateControl:
          type: fixed-load
          opts:
            transactionLoad: 2
        workload:
          module: benchmarks/callbacks/createProfileBenchmark.js
          arguments:
            assets: 10